version: "3"

services:
  postdb:
    container_name: "gobarber"
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_DATABASE: gobarber
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123456"
  db-mongo:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
